locallibrary/locallibrary/catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('books/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
]

urlpatterns += [
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('borrowed/', views.AllBorrowedBooksListView.as_view(), name='all-borrowed'),
]

locallibrary/locallibrary/locallibrary/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

]

urlpatterns += [
    path('catalog/', include('catalog.urls')),
    path('authors/', include('catalog.urls')),
    #path('', RedirectView.as_view(url='/catalog/', permanent= True)),
]

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#Add Django site authentication urls (for login, logout, password management)
urlpatterns+= [
    path('accounts/', include('django.contrib.auth.urls')),
]

locallibrary/locallibrary/catalog/models.py
import uuid
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date

# Create your models here.

class Genre(models.Model):
    """model representing a book genre"""
    name = models.CharField(max_length=200, help_text='Enter book genre')


    def __str__(self):
        """string representation of model object"""
        return self.name
        
class Book(models.Model):
    """Model representing a book(not a specific copy  of a book)"""
    title = models.CharField(max_length=200)

    #foreign key used because book can only have one author, but authors can have many books
    #Author as a string rather than object because it hasn't been declared yet in the file

    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)

    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField('ISBN',max_length=13, help_text='13 character <a href="https://www.isbn-international.org/content/what-isbn">ISBN  number</a>')

    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    genre = models.ManyToManyField('Genre', help_text='select a genre for this book.')

    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        """string for representing the model object"""
        return self.title

    def get_absolute_url(self):
        """returns the url to accesss a detail record for this book"""
        return reverse('book-detail', args=[str(self.id)])
    
    def display_genre(self):
        """Create a string for genre to be used in Admin """
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = 'Genre'

class BookInstance(models.Model):
    """model representing a specific copy of a book"""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey(Book, on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    LOAN_STATUS= (
        ('r', 'Reserved'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('m','Maintenance'),
    )
    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text='book availability' )


    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)
    
    #verify if it is an empty fiels ,Django throws an error because empty values are not comparable
    
    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    def __str__(self):
        """string for representing model object"""
        return f'{self.id}, ({self.book.title})'

class Author(models.Model):
    """model representing an author"""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """returns url to a particular author instance"""
        return reverse('author-detail', args=[str(self.id)])
        
    def __str__(self):
        """string representation the model"""
        return f'{self.last_name},{self.first_name}'

class Language(models.Model):
    """model  representing a language"""
    name = models.CharField(max_length=100, help_text="Enter the book's natural language")

    def __str__(self):
        """string representing the language model"""
        return f"{self.name}"

locallibrary/locallibrary/catalog/views.py
from django.shortcuts import render
from catalog.models import Book, Author, BookInstance, Genre
from django.views import generic
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
# Create your views here.
def index(request):
    """view function for the home page site"""

    #Generate counts of some of the main objects
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_books +1

    #Available Books (status = 'a')
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()

    #The all() is implied by default
    num_authors = Author.objects.count()
    
    context = {
        'num_books' : num_books,
        'num_instances' : num_instances,
        'num_instances_available' : num_instances_available,
        'num_authors' : num_authors,
        'num_visits' : num_visits,
    }
    
    #Render the HTML template index.html with data from the context variable
    return render(request, 'index.html', context=context)

class BookListView(generic.ListView):
   
    '''context_object_name = 'my_book_list'   # your own name for the list as a template variable
    queryset = Book.objects.filter(title__icontains='war')[:5] # Get 5 books containing the title war
    template_name = 'books/my_arbitrary_template_name_list.html'  # Specify your own template name/location'''

    #add model to view
    model = Book
    paginate_by = 2

    #best way to represent queryset

    def get_queryset(self):
        #gets 5 titles containing 'war in the title
        return Book.objects.all()[:5]
    
    """We can override get_context_data() in order to pass additional context variables to the template
            when doing this it is important to follow this pattern:
                1. First get the existing context from our superclass.
                2. Add your new context information.
                3. Return the new (updated) context.

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(BookListView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        context['some_data'] = 'This is just some data'
        return context        
    """
    
class BookDetailView(generic.DetailView):
    """detail view for the books"""
    model = Book

class AuthorListView(generic.ListView):
    """Author list """
    model = Author
    paginate_by = 2
   
class AuthorDetailView(generic.DetailView):
    """details about aauthor"""
    model = Author

class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """class-based view listing books on loan to current user"""
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 5

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')

class AllBorrowedBooksListView(PermissionRequiredMixin, generic.ListView):

    model = BookInstance
    permission_required = "catalog.can_mark_returned"
    template_name = "catalog/bookinstance_list_all_borrowed_books.html"
    paginate_by = 5

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o').order_by('due_back')

locallibrary/locallibrary/catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}

    <h1>Author: {{ author.last_name}}, {{ author.first_name}} </h1>

    <h6>{{ author.date_of_birth }} - {% if author.date_of_death %}{{ author.date_of_death }}{% endif %}</h6>

    <div style="margin-left:20px;margin-top:20px">
        <h4>Books</h4>
        <dl>
            {% for book in author.book_set.all %}
                <dt><a href="{% url 'book-detail' book.pk %}">{{book}}</a> ({{ book.bookinstance_set.all.count}})</dt>
                <dd>{{book.summary}}</dd>
            {% endfor %}  
        </dl>
    </div>
{% endblock %}

locallibrary/locallibrary/catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Author List</h1>
{% if author_list %}
    <ul>           
        {% for author in author_list %}
            <li>
                <a href="{{author.get_absolute_url}}">{{ author }} ({{author.date_of_birth}} - {% if author.date_of_death %}{{author.date_of_death}}{% endif %}) </a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>There are no Authors in the library.</p>
{% endif %}

{% endblock %}

locallibrary/locallibrary/catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Title: {{ book.title }}</h1>


    <p><strong>Author:</strong> <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a></p>
    <p><strong>Summary:</strong> {{ book.summary }}</p>
    <p><strong>ISBN:</strong> {{book.isbn }}</p>
    <p><strong>Language:</strong> {{book.language}}</p>
    <p><strong>Genre:</strong> {{ book.genre.all|join:", "}}</p>

    <div style="margin-left: 20px; margin-top:20px">
        <h4>Copies</h4>

        {% for copy in book.bookinstance_set.all %}
            <hr>
            <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif%}">{{ copy.get_status_display }}</p>
            {% if copy.status != 'a' %}
                <p><strong>Due to be Returned:</strong> {{copy.due_back}}</p>
            {% endif %}
            <p><strong>Imprint:</strong> {{copy.imprint}}</p>
            <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
        {% endfor %}
    </div>
{% endblock %}

locallibrary/locallibrary/catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Book List</h1>
    {% if book_list %}
    <ul>
        {% for book in book_list%}
        <li>
            <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{ book.author }})
        </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>There are no books in te library.</p>
    {% endif %}
    {% endblock %}

locallibrary/locallibrary/catalog/templates/catalog/bookinstance_list_all_borrowed_books.html
{%extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>
    {% if bookinstance_list %}
    <ul>
        {% for bookinst in bookinstance_list %}
        <li class="{% if bookinst.is_overdue %}text-danger{% endif%}">
            <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a>({{ bookinst.due_back}}) {%if user.is_staff %} - <strong>{{ bookinst.borrower}}{% endif %}</strong>
        </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>There are no books borrowed.</p>
    {% endif %}
{% endblock%}

locallibrary/locallibrary/catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %} 
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})        
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}